export interface TocSection {
	id: string
	text: string
	level: number
}

export const tocSections: Record<string, TocSection[]> = {
	'/about/icons': [
		{ id: 'icon-component', text: 'Icon component', level: 2 },
		{ id: 'svg-icons', text: 'SVG icons', level: 2 },
	],
	'/about/quick-start': [
		{ id: 'install', text: 'Install', level: 2 },
		{ id: 'theming', text: 'Theming', level: 2 },
		{ id: 'dark-and-light-color-schemes', text: 'Dark and light color schemes', level: 3 },
		{ id: 'typography', text: 'Typography', level: 2 },
	],
	'/components/autocomplete': [
		{ id: 'usage', text: 'Usage', level: 2 },
		{ id: 'multiple-values', text: 'Multiple values', level: 2 },
		{ id: 'long-option-lists', text: 'Long option lists', level: 2 },
		{ id: 'accessibility', text: 'Accessibility', level: 2 },
		{ id: 'theming', text: 'Theming', level: 2 },
		{ id: 'api', text: 'API', level: 2 },
		{ id: 'attributes', text: 'Attributes', level: 3 },
		{ id: 'autocompleteoption', text: 'AutoCompleteOption', level: 3 },
	],
	'/components/badge': [
		{ id: 'usage', text: 'Usage', level: 2 },
		{ id: 'small-badge', text: 'Small badge', level: 3 },
		{ id: 'large-badge', text: 'Large badge', level: 3 },
		{ id: 'positioning', text: 'Positioning', level: 2 },
		{ id: 'example', text: 'Example', level: 3 },
		{ id: 'api', text: 'API', level: 2 },
		{ id: 'attributes', text: 'Attributes', level: 3 },
	],
	'/components/button': [
		{ id: 'types', text: 'Types', level: 2 },
		{ id: 'elevated-button', text: 'Elevated button', level: 2 },
		{ id: 'filled-button', text: 'Filled button', level: 2 },
		{ id: 'tonal-button', text: 'Tonal button', level: 2 },
		{ id: 'outlined-button', text: 'Outlined button', level: 2 },
		{ id: 'text-button', text: 'Text button', level: 2 },
		{ id: 'icon', text: 'Icon', level: 2 },
		{ id: 'loading', text: 'Loading', level: 2 },
		{ id: 'size', text: 'Size', level: 2 },
		{ id: 'toggle', text: 'Toggle', level: 2 },
		{ id: 'theming', text: 'Theming', level: 2 },
		{ id: 'elevated-button-tokens', text: 'Elevated button tokens', level: 3 },
		{ id: 'elevated-button-example', text: 'Elevated button example', level: 3 },
		{ id: 'filled-button-tokens', text: 'Filled button tokens', level: 3 },
		{ id: 'filled-button-example', text: 'Filled button example', level: 3 },
		{ id: 'tonal-button-tokens', text: 'Tonal button tokens', level: 3 },
		{ id: 'tonal-button-example', text: 'Tonal button example', level: 3 },
		{ id: 'outlined-button-tokens', text: 'Outlined button tokens', level: 3 },
		{ id: 'outlined-button-example', text: 'Outlined button example', level: 3 },
		{ id: 'text-button-tokens', text: 'Text button tokens', level: 3 },
		{ id: 'shared-tokens', text: 'Shared tokens', level: 3 },
		{ id: 'text-button-example', text: 'Text button example', level: 3 },
		{ id: 'api', text: 'API', level: 2 },
		{ id: 'attributes', text: 'Attributes', level: 3 },
		{ id: 'bindables', text: 'Bindables', level: 3 },
	],
	'/components/card': [
		{ id: 'types', text: 'Types', level: 2 },
		{ id: 'elevated-card', text: 'Elevated card', level: 2 },
		{ id: 'filled-card', text: 'Filled card', level: 2 },
		{ id: 'outlined-card', text: 'Outlined card', level: 2 },
		{ id: 'theming', text: 'Theming', level: 2 },
		{ id: 'elevated-card-tokens', text: 'Elevated card tokens', level: 3 },
		{ id: 'filled-card-tokens', text: 'Filled card tokens', level: 3 },
		{ id: 'outlined-card-tokens', text: 'Outlined card tokens', level: 3 },
		{ id: 'api', text: 'API', level: 2 },
		{ id: 'bindables', text: 'Bindables', level: 3 },
	],
	'/components/checkbox': [
		{ id: 'usage', text: 'Usage', level: 2 },
		{ id: 'disabled', text: 'Disabled', level: 2 },
		{ id: 'label', text: 'Label', level: 3 },
		{ id: 'theming', text: 'Theming', level: 2 },
		{ id: 'example', text: 'Example', level: 3 },
		{ id: 'api', text: 'API', level: 2 },
		{ id: 'bindables', text: 'Bindables', level: 3 },
	],
	'/components/chip': [
		{ id: 'assist-chip', text: 'Assist chip', level: 2 },
		{ id: 'outlined', text: 'Outlined', level: 3 },
		{ id: 'elevated', text: 'Elevated', level: 3 },
		{ id: 'disabled', text: 'Disabled', level: 3 },
		{ id: 'as-link', text: 'As link', level: 3 },
		{ id: 'filter-chip', text: 'Filter chip', level: 2 },
		{ id: 'outlined-2', text: 'Outlined', level: 3 },
		{ id: 'elevated-2', text: 'Elevated', level: 3 },
		{ id: 'removable', text: 'Removable', level: 3 },
		{ id: 'disabled-2', text: 'Disabled', level: 3 },
		{ id: 'group', text: 'Group', level: 3 },
		{ id: 'input-chip', text: 'Input chip', level: 2 },
		{ id: 'default', text: 'Default', level: 3 },
		{ id: 'selected', text: 'Selected', level: 3 },
		{ id: 'separate-actions', text: 'Separate actions', level: 3 },
		{ id: 'disabled-3', text: 'Disabled', level: 3 },
		{ id: 'chips-with-text-fields', text: 'Chips with text fields', level: 3 },
		{ id: 'accessibility', text: 'Accessibility', level: 2 },
		{ id: 'theming', text: 'Theming', level: 2 },
		{ id: 'example', text: 'Example', level: 3 },
		{ id: 'api', text: 'API', level: 2 },
		{ id: 'chipset-attributes', text: 'ChipSet attributes', level: 3 },
		{ id: 'assistchip-attributes', text: 'AssistChip attributes', level: 3 },
		{ id: 'filterchip-attributes', text: 'FilterChip attributes', level: 3 },
		{ id: 'inputchip-attributes', text: 'InputChip attributes', level: 3 },
	],
	'/components/date-picker': [
		{ id: 'usage', text: 'Usage', level: 2 },
		{ id: 'anatomy', text: 'Anatomy', level: 2 },
		{ id: 'reacting-to-a-change', text: 'Reacting to a change', level: 2 },
		{ id: 'text-field-variants', text: 'Text field variants', level: 2 },
		{ id: 'localisation', text: 'Localisation', level: 2 },
		{ id: 'first-day-of-the-week', text: 'First day of the week', level: 3 },
		{ id: 'bounding-the-selection', text: 'Bounding the selection', level: 2 },
		{ id: 'disabling-individual-days', text: 'Disabling individual days', level: 3 },
		{ id: 'restricting-the-year-menu', text: 'Restricting the year menu', level: 3 },
		{ id: 'days-of-neighbouring-months', text: 'Days of neighbouring months', level: 2 },
		{ id: 'controlling-the-calendar', text: 'Controlling the calendar', level: 2 },
		{ id: 'opening-it-yourself', text: 'Opening it yourself', level: 3 },
		{ id: 'forms-and-validation', text: 'Forms and validation', level: 2 },
		{ id: 'modal', text: 'Modal', level: 2 },
		{ id: 'keyboard-entry-and-custom-wording', text: 'Keyboard entry and custom wording', level: 3 },
		{ id: 'range', text: 'Range', level: 2 },
		{ id: 'two-fields', text: 'Two fields', level: 3 },
		{ id: 'theming', text: 'Theming', level: 2 },
		{ id: 'example', text: 'Example', level: 3 },
		{ id: 'motion-and-gestures', text: 'Motion and gestures', level: 2 },
		{ id: 'accessibility', text: 'Accessibility', level: 2 },
		{ id: 'api', text: 'API', level: 2 },
		{ id: 'dockeddatepicker', text: 'DockedDatePicker', level: 3 },
		{ id: 'datepickerdialog', text: 'DatePickerDialog', level: 3 },
		{ id: 'daterangepicker', text: 'DateRangePicker', level: 3 },
		{ id: 'calendar-and-yeargrid', text: 'Calendar and YearGrid', level: 3 },
		{ id: 'date-helpers', text: 'Date helpers', level: 3 },
	],
	'/components/dialog': [
		{ id: 'usage', text: 'Usage', level: 2 },
		{ id: 'methods', text: 'Methods', level: 2 },
		{ id: 'scrollable-content', text: 'Scrollable content', level: 2 },
		{ id: 'without-animation', text: 'Without animation', level: 2 },
		{ id: 'accessibility', text: 'Accessibility', level: 2 },
		{ id: 'theming', text: 'Theming', level: 2 },
		{ id: 'api', text: 'API', level: 2 },
		{ id: 'attributes', text: 'Attributes', level: 3 },
	],
	'/components/divider': [
		{ id: 'usage', text: 'Usage', level: 2 },
		{ id: 'theming', text: 'Theming', level: 2 },
		{ id: 'example', text: 'Example', level: 3 },
		{ id: 'api', text: 'API', level: 2 },
		{ id: 'attributes', text: 'Attributes', level: 3 },
	],
	'/components/icon-button': [
		{ id: 'types', text: 'Types', level: 2 },
		{ id: 'icon-button', text: 'Icon button', level: 2 },
		{ id: 'filled-icon-button', text: 'Filled icon button', level: 2 },
		{ id: 'tonal-icon-button', text: 'Tonal icon button', level: 2 },
		{ id: 'outlined-icon-button', text: 'Outlined icon button', level: 2 },
		{ id: 'size', text: 'Size', level: 2 },
		{ id: 'toggle', text: 'Toggle', level: 2 },
		{ id: 'loading', text: 'Loading', level: 2 },
		{ id: 'tooltip', text: 'Tooltip', level: 2 },
		{ id: 'theming', text: 'Theming', level: 2 },
		{ id: 'icon-button-tokens', text: 'Icon button Tokens', level: 3 },
		{ id: 'icon-button-example', text: 'Icon button example', level: 3 },
		{ id: 'filled-icon-button-tokens', text: 'Filled icon button tokens', level: 3 },
		{ id: 'filled-icon-button-example', text: 'Filled icon button example', level: 3 },
		{ id: 'tonal-icon-buttons-tokens', text: 'Tonal icon buttons tokens', level: 3 },
		{ id: 'tonal-icon-button-example', text: 'Tonal icon button example', level: 3 },
		{ id: 'outlined-icon-button-tokens', text: 'Outlined icon button tokens', level: 3 },
		{ id: 'outlined-icon-button-example', text: 'Outlined icon button example', level: 3 },
		{ id: 'api', text: 'API', level: 2 },
		{ id: 'props', text: 'Props', level: 3 },
	],
	'/components/list': [
		{ id: 'usage', text: 'Usage', level: 2 },
		{ id: 'icon-item', text: 'Icon Item', level: 2 },
		{ id: 'theming', text: 'Theming', level: 2 },
		{ id: 'tokens', text: 'Tokens', level: 3 },
		{ id: 'example', text: 'Example', level: 3 },
		{ id: 'accessibility', text: 'Accessibility', level: 2 },
		{ id: 'api', text: 'API', level: 2 },
		{ id: 'list-attributes', text: 'List attributes', level: 3 },
		{ id: 'listitem-attributes', text: 'ListItem attributes', level: 3 },
	],
	'/components/loading-indicator': [
		{ id: 'indeterminate', text: 'Indeterminate', level: 2 },
		{ id: 'determinate', text: 'Determinate', level: 2 },
		{ id: 'contained', text: 'Contained', level: 2 },
		{ id: 'accessibility', text: 'Accessibility', level: 2 },
		{ id: 'theming', text: 'Theming', level: 2 },
		{ id: 'api', text: 'API', level: 2 },
	],
	'/components/menu': [
		{ id: 'usage', text: 'Usage', level: 2 },
		{ id: 'methods', text: 'Methods', level: 2 },
		{ id: 'items', text: 'Items', level: 2 },
		{ id: 'accessibility', text: 'Accessibility', level: 2 },
		{ id: 'theming', text: 'Theming', level: 2 },
		{ id: 'example', text: 'Example', level: 3 },
		{ id: 'api', text: 'API', level: 2 },
		{ id: 'menu-attributes', text: 'Menu attributes', level: 3 },
		{ id: 'menuitem-attributes', text: 'MenuItem attributes', level: 3 },
	],
	'/components/navigation-drawer': [
		{ id: 'usage', text: 'Usage', level: 2 },
		{ id: 'opening-a-modal-drawer', text: 'Opening a modal drawer', level: 2 },
		{ id: 'accessibility', text: 'Accessibility', level: 2 },
		{ id: 'theming', text: 'Theming', level: 2 },
		{ id: 'example', text: 'Example', level: 3 },
		{ id: 'api', text: 'API', level: 2 },
		{ id: 'navigationdrawer-attributes', text: 'NavigationDrawer attributes', level: 3 },
		{ id: 'navigationdraweritem-attributes', text: 'NavigationDrawerItem attributes', level: 3 },
	],
	'/components/navigation-rail': [
		{ id: 'usage', text: 'Usage', level: 2 },
		{ id: 'links', text: 'Links', level: 2 },
		{ id: 'accessibility', text: 'Accessibility', level: 2 },
		{ id: 'theming', text: 'Theming', level: 2 },
		{ id: 'example', text: 'Example', level: 3 },
		{ id: 'api', text: 'API', level: 2 },
		{ id: 'navigationrail-attributes', text: 'NavigationRail attributes', level: 3 },
		{ id: 'navigationrailitem-attributes', text: 'NavigationRailItem attributes', level: 3 },
	],
	'/components/progress': [
		{ id: 'determinate', text: 'Determinate', level: 2 },
		{ id: 'indeterminate', text: 'Indeterminate', level: 2 },
		{ id: 'wavy', text: 'Wavy', level: 2 },
		{ id: 'buffer', text: 'Buffer', level: 2 },
		{ id: 'without-a-track', text: 'Without a track', level: 2 },
		{ id: 'four-colors', text: 'Four colors', level: 2 },
		{ id: 'accessibility', text: 'Accessibility', level: 2 },
		{ id: 'right-to-left', text: 'Right-to-left', level: 2 },
		{ id: 'theming', text: 'Theming', level: 2 },
		{ id: 'circular-progress-tokens', text: 'Circular progress tokens', level: 3 },
		{ id: 'circular-progress-example', text: 'Circular progress example', level: 3 },
		{ id: 'linear-progress-tokens', text: 'Linear progress tokens', level: 3 },
		{ id: 'linear-progress-example', text: 'Linear progress example', level: 3 },
		{ id: 'api', text: 'API', level: 2 },
		{ id: 'circular-progress-attributes', text: 'Circular progress attributes', level: 3 },
		{ id: 'linear-progress-attributes', text: 'Linear progress attributes', level: 3 },
	],
	'/components/radio': [
		{ id: 'usage', text: 'Usage', level: 2 },
		{ id: 'labels', text: 'Labels', level: 3 },
		{ id: 'theming', text: 'Theming', level: 2 },
		{ id: 'example', text: 'Example', level: 3 },
		{ id: 'api', text: 'API', level: 2 },
		{ id: 'bindables', text: 'Bindables', level: 3 },
	],
	'/components/ripple': [
		{ id: 'usage', text: 'Usage', level: 2 },
		{ id: 'theming', text: 'Theming', level: 2 },
		{ id: 'tokens', text: 'Tokens', level: 3 },
		{ id: 'example', text: 'Example', level: 3 },
		{ id: 'api', text: 'API', level: 2 },
		{ id: 'attributes', text: 'Attributes', level: 3 },
		{ id: 'bindables', text: 'Bindables', level: 3 },
	],
	'/components/segmented-button': [
		{ id: 'single-choice', text: 'Single choice', level: 2 },
		{ id: 'multiple-choice', text: 'Multiple choice', level: 2 },
		{ id: 'icons', text: 'Icons', level: 2 },
		{ id: 'disabled', text: 'Disabled', level: 2 },
		{ id: 'api', text: 'API', level: 2 },
		{ id: 'attributes', text: 'Attributes', level: 3 },
		{ id: 'bindables', text: 'Bindables', level: 3 },
	],
	'/components/select': [
		{ id: 'usage', text: 'Usage', level: 2 },
		{ id: 'disabled', text: 'Disabled', level: 3 },
		{ id: 'validation', text: 'Validation', level: 3 },
		{ id: 'multiple-selection', text: 'Multiple selection', level: 3 },
		{ id: 'virtual-list', text: 'Virtual list', level: 3 },
		{ id: 'icons', text: 'Icons', level: 3 },
		{ id: 'theming', text: 'Theming', level: 2 },
		{ id: 'filled-select-tokens', text: 'Filled select tokens', level: 3 },
		{ id: 'filled-select-example', text: 'Filled select example', level: 3 },
		{ id: 'outlined-select-tokens', text: 'Outlined select tokens', level: 3 },
		{ id: 'sizing-tokens', text: 'Sizing tokens', level: 3 },
		{ id: 'outlined-select-example', text: 'Outlined select example', level: 3 },
		{ id: 'api', text: 'API', level: 2 },
		{ id: 'attributes', text: 'Attributes', level: 3 },
		{ id: 'selectoption', text: 'SelectOption', level: 3 },
		{ id: 'bindables', text: 'Bindables', level: 3 },
	],
	'/components/slider': [
		{ id: 'usage', text: 'Usage', level: 2 },
		{ id: 'variants', text: 'Variants', level: 2 },
		{ id: 'sizes', text: 'Sizes', level: 2 },
		{ id: 'orientation', text: 'Orientation', level: 2 },
		{ id: 'steps-and-stop-indicators', text: 'Steps and stop indicators', level: 2 },
		{ id: 'value-indicator', text: 'Value indicator', level: 2 },
		{ id: 'inset-icon', text: 'Inset icon', level: 2 },
		{ id: 'disabled', text: 'Disabled', level: 2 },
		{ id: 'right-to-left', text: 'Right-to-left', level: 2 },
		{ id: 'theming', text: 'Theming', level: 2 },
		{ id: 'example', text: 'Example', level: 3 },
		{ id: 'accessibility', text: 'Accessibility', level: 2 },
		{ id: 'api', text: 'API', level: 2 },
		{ id: 'attributes', text: 'Attributes', level: 3 },
		{ id: 'bindables', text: 'Bindables', level: 3 },
	],
	'/components/snackbar': [
		{ id: 'usage', text: 'Usage', level: 2 },
		{ id: 'single-line-snackbar-2', text: 'Single-line snackbar', level: 3 },
		{ id: 'two-line-snackbar', text: 'Two-line snackbar', level: 3 },
		{ id: 'manual-control', text: 'Manual control', level: 2 },
		{ id: 'theming', text: 'Theming', level: 2 },
		{ id: 'tokens', text: 'Tokens', level: 3 },
		{ id: 'example', text: 'Example', level: 3 },
		{ id: 'api', text: 'API', level: 2 },
		{ id: 'attributes', text: 'Attributes', level: 3 },
		{ id: 'bindables', text: 'Bindables', level: 3 },
		{ id: 'methods', text: 'Methods', level: 3 },
	],
	'/components/switch': [
		{ id: 'usage', text: 'Usage', level: 2 },
		{ id: 'disable', text: 'Disable', level: 2 },
		{ id: 'icons', text: 'Icons', level: 2 },
		{ id: 'theming', text: 'Theming', level: 2 },
		{ id: 'tokens', text: 'Tokens', level: 3 },
		{ id: 'example', text: 'Example', level: 3 },
		{ id: 'api', text: 'API', level: 2 },
		{ id: 'switch', text: 'Switch', level: 3 },
		{ id: 'bindables', text: 'Bindables', level: 3 },
	],
	'/components/tabs': [
		{ id: 'usage', text: 'Usage', level: 2 },
		{ id: 'primary-tabs', text: 'Primary Tabs', level: 3 },
		{ id: 'secondary-tabs', text: 'Secondary Tabs', level: 3 },
		{ id: 'selection', text: 'Selection', level: 3 },
		{ id: 'links', text: 'Links', level: 3 },
		{ id: 'api', text: 'API', level: 2 },
		{ id: 'tabs', text: 'Tabs', level: 3 },
		{ id: 'tab', text: 'Tab', level: 3 },
	],
	'/components/text-field': [
		{ id: 'usage', text: 'Usage', level: 2 },
		{ id: 'input-type', text: 'Input type', level: 3 },
		{ id: 'disabled', text: 'Disabled', level: 3 },
		{ id: 'labels', text: 'Labels', level: 3 },
		{ id: 'textarea', text: 'Textarea', level: 3 },
		{ id: 'icons', text: 'Icons', level: 3 },
		{ id: 'prefix-and-suffix', text: 'Prefix and suffix', level: 3 },
		{ id: 'supporting-text', text: 'Supporting text', level: 3 },
		{ id: 'character-counter', text: 'Character counter', level: 3 },
		{ id: 'validation', text: 'Validation', level: 3 },
		{ id: 'theming', text: 'Theming', level: 2 },
		{ id: 'filled-text-field-tokens', text: 'Filled text field tokens', level: 3 },
		{ id: 'filled-text-field-example', text: 'Filled text field example', level: 3 },
		{ id: 'outlined-text-field-tokens', text: 'Outlined text field tokens', level: 3 },
		{ id: 'shared-tokens', text: 'Shared tokens', level: 3 },
		{ id: 'outlined-text-field-example', text: 'Outlined text field example', level: 3 },
		{ id: 'api', text: 'API', level: 2 },
		{ id: 'attributes', text: 'Attributes', level: 3 },
		{ id: 'bindables', text: 'Bindables', level: 3 },
	],
	'/components/tooltip': [
		{ id: 'basic-tooltip', text: 'Basic tooltip', level: 2 },
		{ id: 'button-with-tooltip', text: 'Button with tooltip', level: 2 },
		{ id: 'positioning', text: 'Positioning', level: 2 },
		{ id: 'touch-devices', text: 'Touch devices', level: 2 },
		{ id: 'accessibility', text: 'Accessibility', level: 2 },
		{ id: 'theming', text: 'Theming', level: 2 },
		{ id: 'api', text: 'API', level: 2 },
		{ id: 'attributes', text: 'Attributes', level: 3 },
	],
}
